# ============================================================
# Pre-commit hooks for Aegis Solutions SaaS Platform
# Ensures code consistency across all Python services
# ============================================================

repos:
  # --- Basic sanity checks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # --- Code formatting (Black) ---
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.11
        args: [--line-length=88]

  # --- Import sorting (isort) ---
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python imports)
        args: ["--profile=black", "--filter-files"]

  # --- Linting (flake8) ---
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-docstrings
          - flake8-comprehensions
        args:
          - --max-line-length=88
          - --ignore=E203,W503
          - --exclude=.venv,venv,__pycache__,migrations,build,dist

  # --- Optional: detect secrets ---
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
