name: Cloud Feature
description: Use for cloud infrastructure/features that span AWS/GCP/Azure.
title: "[Cloud Feature]: "
labels:
  - cloud
  - "type: feature"
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the change, business value, and scope.
    validations:
      required: true
  - type: dropdown
    id: product
    attributes:
      label: Product
      options:
        - payments:iso20022
        - security
        - doc-analyzer
        - privacy:anonymization
    validations:
      required: true
  - type: dropdown
    id: change_type
    attributes:
      label: Change Type
      options:
        - feature
        - fix
        - hotfix
        - perf
        - docs
        - refactor
        - build
        - ci
        - test
        - chore
    validations:
      required: true
  - type: dropdown
    id: change_risk
    attributes:
      label: Change Risk
      options:
        - low
        - medium
        - high
    validations:
      required: true
  - type: checkboxes
    id: cloud_provider
    attributes:
      label: Cloud Provider(s)
      description: Selecting at least one provider autolabels this issue `cloud` and triggers sub-task fan-out.
      options:
        - label: AWS
        - label: Azure
        - label: GCP
    validations:
      required: true
  - type: checkboxes
    id: environment
    attributes:
      label: Environments
      options:
        - label: testing
        - label: staging
        - label: prod
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - infra
        - api
        - security
        - ci-cd
        - mapping-engine
        - validator
        - rule-engine
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
  - type: textarea
    id: rollback
    attributes:
      label: Rollback Plan
    validations:
      required: true
